### ISSUE TITLE
gd crash when i click the comment button

### ISSUE THREAD

**Issue by hodyu** [Cvolton/best-epic-gd-mods#29]

**Comment by Cvolton** [comment]
does it happen consistently or only on some levels? what other mods are you using if any?

**Comment by tungdo0602** [comment]
also happens to me

**Comment by tungdo0602** [comment]
![image](https://github.com/Cvolton/best-epic-gd-mods/assets/89498812/c07c6b73-fdbe-44a6-9fc6-7b00cf3fa338)
all the mod i use

**Comment by tungdo0602** [comment]
also crash when it show up user profile

**Comment by Cvolton** [comment]
do you have a crash log? megahack saves these in the crash-logs directory

**Comment by hodyu** [comment]
I don't remember because it was a long time ago, but I think there was a conflict with gradient mod
https://twitter.com/Sai47618920/status/1653794468624052225 try it

**Comment by Cvolton** [comment]
unfortunately GradientMod is explicitly written in a way that breaks any other mods touching user profiles. I recommend using BitZ's CustomProfile as an alternative
https://www.mediafire.com/file/fv0r2a06d3g6m53/CustomProfile.dll/file

**Comment by tungdo0602** [comment]
> unfortunately GradientMod is explicitly written in a way that breaks any other mods touching user profiles. I recommend using BitZ's CustomProfile as an alternative https://www.mediafire.com/file/fv0r2a06d3g6m53/CustomProfile.dll/file

ty
